_target_: src.datasets.LJDataset
data_dir: "data/LJSpeech-1.1"
spec_transform:
  _target_: src.transforms.MelSpectrogram
  config:
    _target_: src.transforms.MelSpectrogramConfig
target_sr: 22050
limit: None
shuffle_index: False
