_target_: src.model.HiFIGAN
mpd:
  _target_: src.model.discriminators.MPD
  periods: [2, 3, 5, 7, 11]
msd:
  _target_: src.model.discriminators.MSD
gen:
  _target_: src.model.generator.Generator
  in_channels: 80
  hidden_dim: 256
  upsample_kernels: [16, 16, 8]
  mrf_kernels: [3, 5, 7]
  mrf_dilation_rates: [[[1], [2]], [[2], [6]], [[3], [12]]]
