defaults:
  - model: hifigan_v3
  - writer: wandb
  - metrics: tts
  - datasets: ljspeech
  - dataloader: dataloader
  - _self_
mpd_optimizer:
  _target_: torch.optim.AdamW
  lr: 3e-4
  betas: [0.8, 0.99]
  weight_decay: 0.01
msd_optimizer:
  _target_: torch.optim.AdamW
  lr: 3e-4
  betas: [0.8, 0.99]
  weight_decay: 0.01
gen_optimizer:
  _target_: torch.optim.AdamW
  lr: 3e-4
  betas: [0.8, 0.99]
  weight_decay: 0.01
mpd_lr_scheduler:
  _target_: torch.optim.lr_scheduler.StepLR
  gamma: 0.99
  step_size: ${trainer.epoch_len}
msd_lr_scheduler:
  _target_: torch.optim.lr_scheduler.StepLR
  gamma: 0.99
  step_size: ${trainer.epoch_len}
gen_lr_scheduler:
  _target_: torch.optim.lr_scheduler.StepLR
  gamma: 0.99
  step_size: ${trainer.epoch_len}
loss_function:
  _target_: src.loss.Loss
  gen_l_fm: 2
  gen_l_mel: 45
trainer:
  log_step: 50
  n_epochs: 100
  epoch_len: 500
  device_tensors: ["spectrogram", "wav"] # which tensors should be on device (ex. GPU)
  resume_from: null # null or path to the checkpoint dir with *.pth and config.yaml
  device: auto # device name or "auto"
  override: False # if True, will override the previous run with the same name
  monitor: "max test_MulticlassAccuracy" # "off" or "max/min metric_name", i.e. our goal is to maximize/minimize metric
  save_period: 5 # checkpoint each save_period epochs in addition to the best epoch
  early_stop: ${trainer.n_epochs} # epochs for early stopping
  save_dir: "saved"
  seed: 1
